name: Link Checker
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.6
        with:
          args: --verbose --no-progress *.md
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
      - name: Fail with grep
        run:
          check_errors = $(grep "Errors were reported" ./lychee/out.md)
          if [ -n "$check_errors" ]; then
            cat .lychee/out.md
            exit 1
          else
            exit 0
          fi
