name: Link Checker
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'  # every night at midnight
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.6
        with:
          args: --verbose --no-progress *.html *.md
      - name: Fail if there were link errors
        run:
          exit ${{ steps.lychee.outputs.exit_code }}
