name: Link Checker
on: push
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.6
        id: lc
        with:
          args: --verbose --no-progress *.md
      - name: Count broken links
        run: |
            cat ./lychee/out.md
            broken_max=10
            broken=$(grep "://" ./lychee/out.md)
            broken_count=$(echo "://" ./lychee/out.md | wc -l)
            if [ "$broken_count" -gt "$broken_max" ]; then
                echo "Number of broken links (${broken_count}) exceeds maximum allowed number (${broken_max})."
                echo "Broken links: "
                echo "$broken"
                exit 1
            else
                echo "Number of broken links (${broken_count}) less than or equal to maximum allowed number (${broken_max})."
                exit 0
            fi
