name: Link Checker
on:
  schedule:
    - cron: '0 4 1 * *'  # every 1st of the month at 6am UTC+2
  workflow_dispatch:
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.0.6
        with:
          args: --verbose --no-progress *.html *.md
      - name: Fail if there were link errors
        run:
          exit ${{ steps.lychee.outputs.exit_code }}
